spring.application.name=epark-api

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/epark_db
spring.datasource.username=postgres
spring.datasource.password=sua_senha_aqui
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# O 'update' cria ou atualiza as tabelas automaticamente com base nas suas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Fuso horário (Importante para bater os testes de datas de entrada e saída)
spring.jackson.time-zone=America/Sao_Paulo
